### ISSUE TITLE
Stuck at `waiting for network to initialize` after Sidecar worker failure

### ISSUE THREAD

**Issue by hannahhoward** [testground/testground#1263] opened 2021-08-19 02:42 UTC
#### Version information:

Commits all exhibiting the issue:
8e76ab86474215293d647a9d03927cdde4948b61 (master), 71ab494b5ea8a8c54b528aeafb9b6260e62257cf (fix/1230), and eaf986c5bdeb126870217a03b86b8a7cab871b38 ( a few commits back)

Environment:
Apple Silicon M1 + Docker Desktop 3.6.0 (Docker Engine 20.10.18)

#### Description:

Unable to run any testground test plans.
Used https://github.com/protocol/beyond-bitswap/tree/master/testbed/testbed
Used https://github.com/ipfs/go-graphsync/tree/master/testplans/graphsync
Replicated even with just the ping pong test -- `testground run single --plan network --testcase ping-pong --builder=docker:go --runner=local:docker --instances=2`

After docker images build, I see this
`sidecar worker failed: failed to initialise the container: failed to get handle to network namespace: protocol family not supported`
followed by some json that looks something like this:
`	{"host": "unix:///var/run/docker.sock", "container": "97626bb09939f15a9059b0abfa18fd33d7ed6f2c671375d293fb365d1e045254"}`

Then all containers get permaneantly stuck at `waiting for network to initialize`

I tried wiping running docker images and volumes
I tried various settings Docker Desktop for Mac
I tried updating  github.com/vishvananda/netlink to v1.1.0 since that's where the error occurs
I tried rebuilding / reinstalling testground (I.e. rebuilding the sidecar docker image)

My machine used to work for testground. Older sha was one that already was running. Have no idea what might have changed other than:
go 1.15 - go 1.16
whatever upgrades to Docker Desktop / Docker Machine / Linux Kernel since I last ran it (did install an update to docker)

**Comment by nonsense** [comment] 2021-11-11 15:53
I am unable to reproduce this on current master `0b997a1` with Docker Desktop 4.1.1 on macOS (Intel CPU).

<img width="747" alt="Screenshot 2021-11-11 at 16 51 12" src="https://user-images.githubusercontent.com/50459/141327851-d7783864-520b-4e83-b662-765024e73494.png">

I will attempt to try on M1 and see if I can reproduce there.

**Comment by galargh** [comment] 2021-12-06 14:02
I have experienced the exact same behaviour on M1 Pro mac running Monterrey with the following versions:
- testground commit: 84e9dff
- docker client: 20.10.9
- go: 1.16.9
- docker engine: 20.10.10
- containerd: 1.4.11
- runc: 1.0.2
- docker-init: 0.19.0

**Comment by galargh** [comment] 2022-03-11 17:02
FYI, I was able to make the ping-pong example work on my arm64 machine with https://github.com/testground/testground/pull/1296

**Comment by laurentsenta** [comment] 2022-07-20 13:21
Closing, but please feel free to reopen if you see more ARM-related issues.

**Closed by laurentsenta** 2022-07-20 13:21 UTC

**Comment by omritoptix** [comment] 2022-11-17 13:00
For me the issue still occurs on my M1 mack.

Versions:
Docker desktop: 4.10.0
go1.18.4
testground commit : 9c13f3b
