### ISSUE TITLE
Test nodes scaling in EKS

### ISSUE THREAD

**Issue by Kale98** [testground/testground#1410] opened 2022-08-02 09:57 UTC
## Description

We need to test the impact of scaling the cluster on Testground, and determine whether scaling will cause any undiscovered issues.

## What defines this endeavour to be complete?

Perform scaling (both up and down) on both EKS clusters, note any issues that pop up, and measure test performance before and after scaling.

- [ ] Scale up to 2 worker nodes, and run basic (storm and ping-pong) tests. Verify tests are passing.
- [ ] Increment by 8 (up to 10) worker nodes
- [ ] Increment by 10 (up to 20) worker nodes
- [ ] Continue incrementing by 20 up to the theoretical limit, or until we lose cluster integrity and/or performance

For each number of nodes:

- [ ] Verify basic health checks (ping-pong, pod connectivity, etc.) are working
- [ ] Run storm test, and note test success percentage, and execution time, as well as number of tg instances in test

All discovered issues should be reported in comments, as well as "Knowledge Gathered" issue for this sprint.

**Comment by laurentsenta** [comment] 2022-08-03 07:57
Similar to my note on https://github.com/testground/testground/issues/1411 could you share the procedure and the pair we are going to test scaling for in this ticket?

No worry about making things pretty, as long as we can refer to them later,
and other maintainers can catch up on the progress, that's perfect.

**Comment by dektech** [comment] 2022-08-03 11:22
For testing purposes, we are using the following commands:

```
eksctl create cluster --name CLUSTER_NAME --without-nodegroup --region=AWS_REGION
eksctl create nodegroup --cluster CLUSTER_NAME --nodes 2 --region=AWS_REGION
eksctl get nodegroup --cluster CLUSTER_NAME # which gives us the nodegroup name, eg. ng-abcd1234
eksctl scale nodegroup --cluster=CLUSTER_NAME --nodes=5 --nodes-max=5 --nodes-min=2 ng-abcd1234
```
After the NG scales, we first need to verify whether the CNIs have successfully scaled as well - are the new nodes getting proper interfaces and is traffic allowed to flow between nodes.
Then we run `storm` tests and verify the stability of the scaled NG, that is, how many successful/failed runs.

**Comment by laurentsenta** [comment] 2022-08-04 08:47
Got it,
so I guess we're going to do something like the following:

```
scale to 2 nodes
[run tests, verify stability]
scale to 4 nodes
[run tests, verify stability]
scale to 8 nodes
[run tests, verify stability]
scale to 16 nodes
[run tests, verify stability]
```

Can you share what the test plan looks like?
I assume it's a matrix of `tests (ping, storm, etc) x CNI combinations x number of nodes`?

**Comment by dektech** [comment] 2022-08-05 13:20
Something similar yeah. Currently I think we have managed to find a stable way to scale the nodes without CNIs losing connectivity, and need to verify that solution first.
After we are sure that works, we can focus on running load tests, as explained in #1411

**Comment by dektech** [comment] 2022-08-16 14:24
This is still a work in progress, because we have encountered some issues with CNIs and scaling. But now with the introduced fixes mentioned in #1389, we can continue working on scaling and testing. 

One thing we have achieved is to prove that `AWS VPC CNI / weave` combo performs just like the `calico / weave` one, in terms of maximum number of pods, and time needed to run a scheduled task. 
I would like to test this with autoscaling just to be sure, but we would then be able to eliminate some overhead and simply use the out-of-the-box CNI as the underlying one.

One important aspect we have to take into consideration is scaling down. If we are to have a cluster with the minimum number of 5 nodes for example, and we scale it up to 15 nodes for a test, it will scale down to 5 nodes after the test is done.
This is where we are still encountering some issues with multus, and need to work on having it function properly when frequent scaling is happening.

**Comment by BigLep** [comment] 2022-08-26 20:31
I'd like the done criteria to be more precise.  Things to include:
1. What are we scaling up to?
2. What are we incrementing by for each round of scaling?
3. When we say "measure test performance before and after scaling", do we mean we'll report on test success percentage, test execution time, or something else?  Please be clear.
4. Where are we noting "any issues that pop up"?

It's not part of the done criteria, please specify what test we are going to run before/after scaling.

**Comment by galargh** [comment] 2022-09-01 07:36
To add to what Steve said, when you say `This is where we are still encountering some issues with multus` I'd like to be able to look up what issues those are. Why don't we start creating GitHub issues for things like that and linking them to this issue for example? 

Could we also mention in the done criteria the exact CNI combos that we want to verify? Some explanation as to why those in the issue description could be useful too - can be as simple as links to other issues where we investigated CNI combinations and where it was summarised what are the advantages/disadvantages of using them.

**Comment by galargh** [comment] 2022-09-02 07:19
> This is a document in the making; I must gather all the notes and list them together

Got it. What I was suggesting as an alternative, and possibly a preferred default when going forward, was to start creating GitHub Issues as soon as you encounter a new issue with the cluster. That way you wouldn't have to go back through all the notes because all the info we need would have already been shared. Even a single "catch-all" issue where you collect your notes as you go might work.

Like this "multus scaling issue" you're describing here. I think it'd have been perfect for a separate GitHub issue. It has a clear problem description - _"multus was simply unable to assign interfaces to pods without a restart"_, a clear solution candidate - _"introducing a custom configmap for the multus daemonset"_, and finally clear acceptance criteria - _"~10 scaling tests"_.

**Comment by BigLep** [comment] 2022-09-07 18:58
@dektech : what's the status here?  This seems like a pretty small task.  I'd ideally like to see a table with the results and where we're at.

**Comment by dektech** [comment] 2022-09-07 22:18
We have benchmarked both `calico/weave` and `vpc/weave` clusters up to 3000 pods and have probably reached some limits.
Preparing a report that will be shared in the following days.

**Comment by brdji** [comment] 2022-09-08 15:19
I have attached the benchmark reports (using the `storm` test) for both clusters. Here's a brief summary:
- Both clusters hit limits around 2000-2200 pods. We have tried increasing the number of nodes, and the resources allocated for the sync-service and sidecar, but these resources have not changed test performance past the specific number. In other words, we seem to be hitting other software or hardware limits that we need to figure out.
- We did not focus on finding the 'magic' number between 2200 and 2700 where tests fail, so we can assume for now that it is 2200.

Possible options to increase the cluster performance:
- We can try adding more nodes to the node group(s), but we have noticed that this did not affect test performance for the AWS - VPC cluster
- We can try upgrading the worker nodes from `c5.4xlarge` to `c5.9xlarge`


[CNI benchmark - VPC.pdf](https://github.com/testground/testground/files/9528104/CNI.benchmark.-.VPC.pdf)
[CNI benchmark - calico.pdf](https://github.com/testground/testground/files/9528103/CNI.benchmark.-.calico.pdf)

**Comment by galargh** [comment] 2022-09-12 14:25
> In other words, we seem to be hitting other software or hardware limits that we need to figure out.

Trying to estimate the priority of this. Could you remind me what's the minimal number of pods we require that we agreed upon? How far are we from meeting that requirement? 

Given the results, are we ready to focus on a single combination?

**Comment by BigLep** [comment] 2022-09-13 16:31
2022-09-13 conversation: before closing, please link on how to reproduce the results.

**Comment by brdji** [comment] 2022-09-14 10:51
We've decided to use the VPC + Weave combination for the EKS cluster. More detailed explanation can be found here:
https://github.com/testground/testground/issues/1411#issuecomment-1230801038

The benchmark script used to generate the results posted above can be found here, in case future benchmarks are required:
https://github.com/testground/testground/issues/1411#issuecomment-1203816117

**Closed by brdji** 2022-09-14 10:51 UTC
Labels: Bloxico, Sprint 12
